buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.flywaydb:flyway-database-postgresql:13.5.0'
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.flywaydb.flyway' version '13.5.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation "org.mybatis.spring.boot:mybatis-spring-boot-starter:4.1.0"

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

def databasePropertiesFile = rootProject.file('database.properties')
def databaseProperties = new Properties()

if (!databasePropertiesFile.exists()) {
    throw new GradleException("database.properties was not found: ${databasePropertiesFile}")
}

databasePropertiesFile.withInputStream { databaseProperties.load(it) }

flyway {
    url = databaseProperties.getProperty('database.url')
    user = databaseProperties.getProperty('database.username')
    password = databaseProperties.getProperty('database.password')
    locations = ['filesystem:src/main/resources/db/migration']
}
