spring.application.name=TodoApp
spring.config.import=optional:file:./database.properties
spring.datasource.url=${DB_URL:${database.url:jdbc:postgresql://localhost:5432/todo_app}}
spring.datasource.username=${DB_USERNAME:${database.username:postgres}}
spring.datasource.password=${DB_PASSWORD:${database.password:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

mybatis.configuration.map-underscore-to-camel-case=true

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}
