CREATE TABLE todo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    detail TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO todo (title, detail, is_completed)
VALUES
    ('Spring Boot 4.1.1', 'Spring Boot 4.1.1 と Java 21 の構成を確認する', TRUE),
    ('MyBatis External SQL', 'ExternalSqlProvider から SQL ファイルを参照する', FALSE),
    ('Next.js + TypeScript', 'フロントエンドの Todo 操作を確認する', FALSE);
